### ISSUE TITLE
Application seems to have issue with using flutter web

### ISSUE THREAD

**Issue by tovganesh** [FusionAuth/fusionauth-example-flutter-dart#7]
Hello,
I tried to add web compilation for this app using flutter create.
However, when I run and try to test the long, I get the following error:

`login error: MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel
crossingthestreams.io/flutter_appauth)`

I am quite new to using FusionAuth, so was wondering if this support or missing altogether or I need to perform additional steps to support flutter web?

**Comment by mooreds** [comment]
@tovganesh sorry you're running into issues. Please check out our flutter quickstart which we've revised and should work.

https://fusionauth.io/docs/quickstarts/quickstart-flutter-native

I'm going to archive this repository because it is out of date, will also close out this issue.
